---
version: '3.8'

services:
  directory:
    image: dalibo/samba:latest
    build: .
    volumes:
      - ./entrypoint-init.d:/docker-entrypoint-init.d/
    environment:
        REALM: samba.docker
        DNS_BACKEND: "NONE"
        ADMIN_PASS: "Long5Ecret"
    command: [
      --debuglevel=3,
    ]
